[package]
name = "slither-io-server"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.18.0"
rand = "0.9.1"
tokio = { version = "1.32.0", features = ["full"] }
bytes = "1.5.0"
log = "0.4.20"
env_logger = "0.10.1"
uuid = { version = "1.4.1", features = ["v4"] }
